//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class liriousdbEntities1 : DbContext
    {
        public liriousdbEntities1()
            : base("name=liriousdbEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<tb_benefits> tb_benefits { get; set; }
        public DbSet<tb_department> tb_department { get; set; }
        public DbSet<tb_discounts> tb_discounts { get; set; }
        public DbSet<tb_employees> tb_employees { get; set; }
        public DbSet<tb_financial> tb_financial { get; set; }
        public DbSet<tb_function> tb_function { get; set; }
        public DbSet<tb_timecard> tb_timecard { get; set; }
    }
}
