//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_benefits
    {
        public int id_benefits { get; set; }
        public int id_emp { get; set; }
        public Nullable<decimal> vl_familySalary { get; set; }
        public Nullable<decimal> vl_food { get; set; }
        public Nullable<decimal> vl_meal { get; set; }
        public Nullable<decimal> vl_transport { get; set; }
        public Nullable<decimal> vl_lifeInsurance { get; set; }
        public Nullable<decimal> vl_planHealth { get; set; }
    }
}
