//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_benefits
    {
        public int id_benefits { get; set; }
        public int id_emp { get; set; }
        public Nullable<bool> vl_food { get; set; }
        public Nullable<bool> vl_transport { get; set; }
        public Nullable<bool> vl_meal { get; set; }
        public Nullable<bool> vl_lifeSafe { get; set; }
        public Nullable<bool> vl_planHealth { get; set; }
        public Nullable<bool> vl_planDental { get; set; }
    }
}
