//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_busline
    {
        public int id_employees { get; set; }
        public string cd_line1 { get; set; }
        public string cd_line2 { get; set; }
        public string cd_line3 { get; set; }
        public string cd_line4 { get; set; }
    }
}
