//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_dependents
    {
        public int id_dependents { get; set; }
        public int id_employees { get; set; }
        public string nm_dependents { get; set; }
        public System.DateTime ds_birthDate { get; set; }
        public bool ds_familySalary { get; set; }
        public bool ds_pension { get; set; }
        public bool ds_irrf { get; set; }
    }
}
