//------------------------------------------------------------------------------
// <auto-generated>
//    O código foi gerado a partir de um modelo.
//
//    Alterações manuais neste arquivo podem provocar comportamento inesperado no aplicativo.
//    Alterações manuais neste arquivo serão substituídas se o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_employees
    {
        public tb_employees()
        {
            this.tb_department = new HashSet<tb_department>();
            this.tb_discounts = new HashSet<tb_discounts>();
            this.tb_financial = new HashSet<tb_financial>();
            this.tb_function = new HashSet<tb_function>();
            this.tb_timecard = new HashSet<tb_timecard>();
        }
    
        public int id_emp { get; set; }
        public string nm_firstName { get; set; }
        public string nm_lastName { get; set; }
        public int vl_qtdDependents { get; set; }
        public string ds_sex { get; set; }
        public System.DateTime dt_birth { get; set; }
        public string ds_cpf { get; set; }
        public string ds_rg { get; set; }
        public string ds_country { get; set; }
        public string ds_state { get; set; }
        public string ds_cep { get; set; }
        public string ds_address { get; set; }
        public string ds_complement { get; set; }
        public string mr_cellphone { get; set; }
        public string mr_tellphone { get; set; }
        public string ds_email { get; set; }
        public string ds_password { get; set; }
        public System.DateTime dt_hiring { get; set; }
        public System.DateTime dt_resignation { get; set; }
    
        public virtual ICollection<tb_department> tb_department { get; set; }
        public virtual ICollection<tb_discounts> tb_discounts { get; set; }
        public virtual ICollection<tb_financial> tb_financial { get; set; }
        public virtual ICollection<tb_function> tb_function { get; set; }
        public virtual ICollection<tb_timecard> tb_timecard { get; set; }
    }
}
