//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Liriou_s_Burguer.Database.Entities
{
    using System;
    using System.Collections.Generic;
    
    public partial class tb_timecard
    {
        public int id_timecard { get; set; }
        public int id_emp { get; set; }
        public System.TimeSpan vl_input { get; set; }
        public System.TimeSpan vl_output { get; set; }
        public System.DateTime dt_date { get; set; }
        public System.TimeSpan vl_cameIn { get; set; }
        public System.TimeSpan vl_exited { get; set; }
        public System.TimeSpan vl_intervalInput { get; set; }
        public System.TimeSpan vl_intervalOutput { get; set; }
        public System.TimeSpan vl_fixedIntInput { get; set; }
        public System.TimeSpan vl_fixedIntOutput { get; set; }
        public System.TimeSpan vl_hoursHealth { get; set; }
    }
}
